# Chapter 1 万物皆数 | 《数学要素》 | 从加减乘除到机器学习

In [2]:
# Bk_Ch1_01
# use python buildin Math library print irrational numbers
# Import math library
import math

# Print the value of PI
print('PI = ', math.pi)

# Print the value of e
print('e = ', math.e)

#Print the value of square root of 2
print('sqrt(2) = ', math.sqrt(2))

PI =  3.141592653589793
e =  2.718281828459045
sqrt(2) =  1.4142135623730951


In [13]:
# Bk_Ch1_02
from mpmath import mp

# set the number precision
mp.dps = 1000 + 1

print('print 1000 digits of PI behind decimal point')
print(mp.pi)

print('print 1000 digits of e behind decimal point')
print(mp.e)

print('print 1000 digits squart root of 2 PI behind decimal point')
print(mp.sqrt(2))


print 1000 digits of PI behind decimal point
3.14159265358979323846264338327950288419716939937510582097494459230781640628620899862803482534211706798214808651328230664709384460955058223172535940812848111745028410270193852110555964462294895493038196442881097566593344612847564823378678316527120190914564856692346034861045432664821339360726024914127372458700660631558817488152092096282925409171536436789259036001133053054882046652138414695194151160943305727036575959195309218611738193261179310511854807446237996274956735188575272489122793818301194912983367336244065664308602139494639522473719070217986094370277053921717629317675238467481846766940513200056812714526356082778577134275778960917363717872146844090122495343014654958537105079227968925892354201995611212902196086403441815981362977477130996051870721134999999837297804995105973173281609631859502445945534690830264252230825334468503526193118817101000313783875288658753320838142061717766914730359825349042875546873115956286388235378759375195778185

In [43]:
# TODO: use seaborn library draw 1000 digits of pi behaid deciaml point's heatmap

In [15]:
# Bk3_Ch1_03
# judgement a number is even or odd
num = float(input("Enter a number: "))

if num.is_integer():
    if(num % 2 == 0):
        print(f'{num} is even.')
    else:
        print(f'{num} is odd')
else:
    print(f'{num} is not an integer.')

Enter a number:  654
654.0 is even.


## 加减法

### 加法

In [14]:
# Bk3_Ch1_04

num1 = 2
num2 = 3

# add two number
sum = num1 + num2

# display the computation
print(f'The sum of {num1} and {num2} is {sum}')

The sum of 2 and 3 is 5


In [15]:
# Bk3_Ch1_05

# user input numbers
num1 = input('Enter addend number: ')
num2 = input('Enter summand number: ')

# add two numbers
sum = float(num1) + float(num2)

# display the computation
print(f'The sum of {num1} and {num2} is {sum}.')

The sum of 54 and 45 is 99.0.


### 累计求和
累计求和的结果不是一个数字，而是一个数列。  
例如:  
  因为，  
    1 = 1  
    1 + 2 = 3  
    1 + 2 + 3 = 6  
    1 + 2 + 3 + 4 = 10  
    1 + 2 + 3 + 4 + 5 = 15  
    1 + 2 + 3 + 4 + 5 + 6 = 21  
    1 + 2 + 3 + 4 + 5 + 6 + 7 = 28  
    1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 = 36  
    1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 = 45  
    1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55  
  故，  
  自然数1到10的累计求和的结果是:  
  1, 3, 6, 10, 15, 21, 28, 36, 45, 55  
  
**累计求和在机器学习中很常用**

In [20]:
# Bk3_Ch1_06
import numpy as np

a_i = np.linspace(1, 10, 10)
print(a_i)

a_i_cumsum = np.cumsum(a_i)
print(a_i_cumsum)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]


### 减法

In [1]:
# Bk_Ch1_07

num1 = 5
num2 = 3

# minus two number
diff = num1 - num2

# display the computation
print(f'The difference of {num1} and {num2} is {diff}.')

The difference of 5 and 3 is 2.


### 相反数

5的相反数是-5(negative five)

## 向量
线性代数在机器学习中是最重要的数学知识
向量分行向量和列向量  
如下面对代码运行结果所示：a为行向量，b为列向量

In [7]:
# use numpy define row vector and column vector
import numpy as np
# row vector
a = np.array([[1,2,3]])
print(a)
# colum vector
b = np.array([[1],[2],[3]])
print(b)

[[1 2 3]]
[[1]
 [2]
 [3]]


### 向量转置
行向量转置（transpose）得到列向量，列向量转置的导航向量，符号标记为右上角一个$\rm T$。  
行向量转置时，顺时针转动90度成为列向量。列向量转置时，逆时针旋转90度得到行向量。

一般的，$A$表示一个矩阵，$a$表示一个向量。  
$[a_1,a_2,a_3,\cdots\,a_n]$，读作"$n$ row vector, $a$ sub one, $a$ sub two, $a$ sub three, dot dot dot, $a$ sub $n$"

In [5]:
# BK_Ch1_08
# use numpy to transpose a vector
import numpy as np

a = np.array([[1,2,3]])
b = np.array([[4],[5],[6]])
# transpose a row vector to column vector
a_tranposed = a.T
print('transposed a row vector:')
print(a_tranposed)
# transpose a column vector to row vector
b_transposed = b.T
print('transposed a column vectr:')
print(b_transposed)

transposed a row vector:
[[1]
 [2]
 [3]]
transposed a column vectr:
[[4 5 6]]


## 矩阵
矩阵(matrix)是将数字排列成表格，$n$行$D$列（记作$n \times D$，读作"$n$ by capital $D$"）  
$n$是矩阵的行数，读作"number of rows in the matrix"  
$D$是矩阵的列数，读作"number of columns in the matrix"

矩阵$X$中，元素(element)$x_{ij}$被称作$ij$元素($ij$ entry or $ij$ element)  
元素$x_{ij}$表示矩阵$X$中的第$i$行，第$j$列元素，读作"appears in row $i$ and column $j$"

In [9]:
# BK_Ch1_09
# use numpy to define a matrix and pick up an element or some elements
import numpy as np

# define a matrix called A
A = np.array([[1,2,3],
             [4,5,6]])

# saved as one dimension row. dimension:（空间的）纬度，范围
# guess:selected first colum from matrix and transposed to a row 
A_first_col = A[:, 0]
print('A_first_col:')
print(A_first_col)
# saved as a column
A_first_col_V2 = A[:,[0]]
print('A_first_col_V2:')
print(A_first_col_V2)
# extract first and second columns
A_first_second_col_V2 = A[:,[0, 1]]
print('A_first_second_col_V2:')
print(A_first_second_col_V2)
# extract first and third columns
A_first_third_col_V2 = A[:,[0, 2]]
print('A_first_third_col_V2:')
print(A_first_third_col_V2)
# extract first row
A_first_row = A[[0], :]
print('A_first_row:')
print(A_first_row)
# extract second row
A_second_row = A[[1], :]
print('A_second_row:')
print(A_second_row)
# pick up i=2,j=1
A_second_row_first_col = A[[1],[0]]
print('A_second_row_first_col:')
print(A_second_row_first_col)

A_first_col:
[1 4]
A_first_col_V2:
[[1]
 [4]]
A_first_second_col_V2:
[[1 2]
 [4 5]]
A_first_third_col_V2:
[[1 3]
 [4 6]]
A_first_row:
[[1 2 3]]
A_second_row:
[[4 5 6]]
A_second_row_first_col:
[4]


全套书使用鸢尾花卉数据集，全程安德森鸢尾花卉数据集(Anderson's Iris data set)进行学习

### 矩阵分块
矩阵分块的视角很重要，一个矩阵可以看做一排列向量，或者是一组行向量
故，形状为$x \times D$的矩阵$X$，可以有如下两种表达：  
1.D个左右排列的列向量 
$$
​	​	​	X_{nD} = [x_1 \quad x_2 \quad \cdots \quad x_D]  
$$
​​	 其中$x_D$为有$n$个元素的的列向量  

2.上下叠放的$n$个行向量
$$
X_{nD} = 
\begin{bmatrix}
    x^{(1)} \\
    x^{(2)} \\
    \cdots  \\
    x^{(n)} \\
\end{bmatrix}
$$
​​	 其中，$x^{(n)}$为一个有$D$个元素的行向量

### 矩阵转置
矩阵转置(matrix transpose)是将矩阵的行列互换得到新的矩阵。
如：
$$
\begin{bmatrix}
    1 & 2  \\
    3 & 4  \\
    5 & 6  \\
\end{bmatrix}_{3 \times 2}=
\begin{bmatrix}
  1 & 3 & 5 \\
  2 & 4 & 6 \\
\end{bmatrix}_{2 \times 3}
$$

矩阵$A$可以写成三个列向量左右排列$[a_1,a_2,a_3]$，对$A$转置的结果是：
$$
A^{\rm T}= 
[a_1 \quad a_2 \quad a_3]^{\rm T}=
\begin{bmatrix}
  a_1^{\rm T} \\
  a_2^{\rm T} \\
  a_3^{\rm T} \\
\end{bmatrix}
$$

例如：
$$
\begin{bmatrix}
  1&4&7\\
  2&5&8\\
  3&6&9
\end{bmatrix}^{\rm T}=
\begin{bmatrix}
\begin{bmatrix}
  1\\
  2\\
  3
\end{bmatrix}&
\begin{bmatrix}
  4\\
  5\\
  6
\end{bmatrix}&
\begin{bmatrix}
  7\\
  8\\
  9
\end{bmatrix}
\end{bmatrix}^{\rm T}=
\begin{bmatrix}
\begin{bmatrix}
  1&2&3
\end{bmatrix}\\
\begin{bmatrix}
  4&5&6
\end{bmatrix}\\
\begin{bmatrix}
  7&8&9
\end{bmatrix}
\end{bmatrix}=
\begin{bmatrix}
  1&2&3\\
  4&5&6\\
  7&8&9
\end{bmatrix}
$$

### 矩阵的形状

先有一个大致的了解

### 矩阵加减

**形状相同，对应位置，批量加减**

In [41]:
# Bk_Ch1_10
import numpy as np
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# by original python function、
print([x + y for x, y in zip(list1, list2)])
print(list(map(lambda x,y:x+y, list1, list2)))

# by numpy library function
x = np.array(list1)
y = np.array(list2)
print(x + y)
print(np.multiply(list1, list2))

[5, 7, 9]
[5, 7, 9]
[5 7 9]
[ 4 10 18]


用for循环解决矩阵加减是最费力的方法。例如上面的代码，最常用的办法是向量化（vectorize）。  
即，尽量采用向量运算避免循环计算

In [3]:
# Bk_Ch1_11
# use original python to complete vector plus and minus
import time
A = [[1, 2, 3],
     [4, 5, 6]]
B = [[1, 0, 0],
     [0, 1, 0]]

t_before = time.perf_counter()
A_plus_B = [[A[i][j] + B[i][j]
            for j in range(len(A[0]))]
            for i in range(len(A))]
t_after = time.perf_counter()
print(A_plus_B)
print(f'costed time:{t_after - t_before:.8f}s')


[[2, 2, 3], [4, 6, 6]]
costed time:0.00017710s


In [14]:
# Bk_Ch1_12
# use numpy library to complete vector plus and minus
import time
import numpy as np

A = [[1, 2, 3],
     [4, 5, 6]]
B = [[1, 0, 0],
     [0, 1, 0]]
t_before = time.perf_counter()
result = np.array(A) + np.array(B)
t_after = time.perf_counter()
print(f'costed time:{t_after - t_before}s')
print(result)

t_before = time.perf_counter()
result = np.add(A, B)
t_after = time.perf_counter()
print(f'costed time:{t_after - t_before}s')
print(result)

costed time:9.590000263415277e-05s
[[2 2 3]
 [4 6 6]]
costed time:0.00010200001997873187s
[[2 2 3]
 [4 6 6]]
